server:
  port: 8088

logging:
  level:
    root: info

app:
  dir:
    imgdir: file:///C:/Workspace/JavaWorkspace/Digital-Hanaro-Spring-Practice/sb2/imgs
    logdir: file:///C:/Workspace/JavaWorkspace/Digital-Hanaro-Spring-Practice/sb2/logs