server:
  port: 81
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: user01
    password: 111111
mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info

app:
  dir:
    imgdir: file:C:/Workspace/JavaWorkspace/Digital-Hanaro-Spring-Practice/imgs/ #화면 출력용
    uploadimgdir: C:/Workspace/JavaWorkspace/Digital-Hanaro-Spring-Practice/imgs/ #파일 write용
    logdir: file:C:/Workspace/JavaWorkspace/Digital-Hanaro-Spring-Practice/logs/
  url:
    server-url: http://172.16.20.169:81 #내 컴퓨터 ip
  key:
    wkey: NnOnJEKXvopIFIhBe2QgBXhLNfkDn1AyyY1IiMcKx2TutRSVVb8Cf9t%2FTQLz8p5moigWyrsLLrulQWrUP%2BjlMw%3D%3D
    whkey: 04670200d6dfdffa3a158c9401f2104a
    ncp-id: tlxux2zvam
    ncp-secret: bDrglALkBbwOlram9XW6rXglz5QToXZjn5RacsA5